- content/issues/2021-04-15-jira-upgrade.md
The Linux Foundation team that maintains our Jira instance will install a Jira update and operating system updates.
Maintenance details:
What:
- issues.jenkins.io
Why:
- upgrade jira to 8.13.5 (latest LTS)
- install OS security updates
- reboot jira instance
Maitenance duration: 1h. Short downtime is expected for 10-20min as we
need to reboot that system
[Discussion](https://groups.google.com/d/msgid/jenkinsci-dev/41268990-aa48-4612-bb71-87d3caf8ed2en%40googlegroups.com)
> Add jira maintenance window

- README.adoc
- content/issues/2021-04-14-maintenance-publick8s.md
[INFRA-2944](https://issues.jenkins.io/browse/INFRA-2944)
[NOTES](https://hackmd.io/EDpvZx9ZS2GWgHHqWFRDfQ?view)
We'll do an AKS cluster upgrade.
The service ldap.jenkins.io service will be restarted.
The procedure upgrade one machine at a time so most services should remain up and running, excepted release.ci, infra.ci and the ldap service will be restarted in the process.
We didn't identify major risk for this upgrade
We are continuously improving the process so, feel free to provides feedbacks on the notes and we will incorporate them in the next upgrades.
> Announce k8s cluster update

- content/issues/2021-04-19-get-jenkins-io-disk-quota-exceeded.md
Azure file storage cannot be mounted.
> Add get.jenkins.io outage 2021-04-19

- content/issues/2021-05-25-weekly-windows.md
Ref. https://hackmd.io/@jenkins-infra/SJNjA5jKu
I saw https://github.com/jenkins-infra/jenkins.io/issues/4387 and I wondered if the user might have been affected.
In any case, it's good thing to add the incident even afterwards, so we can point the history later if needed.
> Add Windows Weekly Package Unavailable Incident

- content/issues/2021-05-29-no-aci-agents-for-ci-jenkins-io.md
See https://hackmd.io/XBFjAgkFQ1mjiKPnsW2EXw for detailed timeline and exploration.  Plugin upgrade seems to have blocked allocations of ACI agents.
Signed-off-by: Mark Waite <mark.earl.waite@gmail.com>
> Note ACI agent allocation outage on ci.jenkins.io

- content/issues/2021-05-29-no-aci-agents-for-ci-jenkins-io.md
Include detailed timeline in the outage file.  May need to remove it if it overflows presentation boundaries on the site.
> Resolve ACI agent outage on ci.jenkins.io

- content/issues/2021-06-01-updates-job-blocked.md
Job is blocked because agent-1 is not available.
> Add outage for update center job on trusted.ci.jenkins.io

- content/issues/2021-07-07-update-center-not-refreshed.md
The web page at https://updates.jenkins.io/latest/ has not been updated in the last 31 hours. It is missing the most recent release of the tuleap-api-plugin that was made about 23 hours ago. The link https://updates.jenkins.io/latest/tuleap-api.hpi should point to tuleap-api-plugin 2.3.0 but instead points to tuleap-api-plugin 2.2.2.
The update center job trying to update the page reports a failure when downloading that plugin from artifactory. However, when I download interactively using the same URL, it succeeds.
> New plugin releases not reported to updates.jenkins.io

- .gitmodules
For some reason that I still ignore updatecli doesn't work if we use a git URL so I am switching to a https for now
> Switch gitsubmodule url from git to https

- content/issues/2021-07-16-archives-jenkins-io-unreachable.md
Record the 15 hour outage of archives.jenkins.io HTTP and HTTPS services.  Computer was running and responding to ssh.  HTTP service was reported as healthy by systemctl, yet wget and web browser could not open the page, even from the host itself.
Stopped and started the apache2 service and that resolved the issue.
> Add archives.jenkins.io outage and its resolution

- content/issues/2021-08-29-wiki-maintenance.md
Announce wiki SSL certificate renewal.  Certificate was reporting that it would expire in 14 days, even though the updated certificate was available.  Restarted the Apache web server to use the new certificate.
Signed-off-by: Mark Waite <mark.earl.waite@gmail.com>
> Announce wiki SSL certificate renewal

- content/issues/2021-09-02-wiki-offline.md
> Note that Jenkins wiki is offline intentionally

- .github/.dependabot.yaml
- .github/workflows/hugo.yaml
- .github/workflows/updatecli.yaml
- .gitignore
- Dockerfile
- docker-compose.yaml
- updatecli/updatecli.d/hugo.yaml
- updatecli/values.github-action.yaml
- updatecli/values.yaml
(edited)
This PR simplifies the updatecli upgrade process for hugo version:
- Stop using a Dockerfile (use the extended Hugo Docker Image instead)
- Fix docker-compose.yaml to work with the Hugo version >= 0.88 (no more read-only sharing)
- Update the updatecli manifest to these changes
- Simplify the updatecli manifest to use the latest "file matchPattern" from updatecli version >= 0.13
- Ensure that updatecli is allowed to upgrade the github workflow file by using our bot account
It also updates the github workflow to:
- Run once per week (instead of every 15 min...)
- Run the "updatecli diff" on ALL PR and commits (to ensure we don't break updatecli in a PR)
- Only run the updatecli "apply" on the principal branch
> chore(updatecli) simplify updatecli process

- content/issues/2022-01-12-maintenance-window-ci.md
> Log ci.jenkins.io upgrade from 2.319.1 to 2.319.2

- content/issues/2022-01-17-repo-jenkins-ci-org.md
> Note that repo.jenkins-ci.org was down

- content/issues/2022-01-13-issue-ci.md
Reverts jenkins-infra/status#111
ci is slow again today...
Ref: https://github.com/jenkins-infra/helpdesk/issues/2733#issuecomment-1014584592 & https://github.com/jenkins-infra/helpdesk/issues/2742
> Revert "chore: close ci.jenkins.io disruption notice"

- content/issues/2022-01-13-issue-ci.md
https://groups.google.com/g/jenkins-infra/c/j7M49evRXJg/m/3UhhLNl9AQAJ states that the issue is resolved.  Builds running early Jan 22, 2022 were not showing any timeout issues.  The repo.jenkins-ci.org performance was sufficient to prevent build timeouts.
> ci.jenkins.io disruption resolved yesterday

- content/issues/2022-01-13-issue-ci.md
Earlier commit #115 said it was resolved, but did not mark it resolved
> Mark the repo outage as resolved

- updatecli/updatecli.d/hugo.yaml
That PR should fix the error on the GH workflow "updatecli".
It also closes #102 (superseeding).
> chore(updatecli) fix manifest syntax to be compliant with 0.18.x

- content/issues/2022-02-09-maintenance-window-ci.md
Start time is a guess, not a commitment.
> Security advisory 2022-02-09 upgrade for ci.jenkins.io

- content/issues/2022-02-16-maintenance-window-ci.md
Correctly record the scheduled 2022-02-16 maintenance window.
> Use notice instead of down for future events

- content/issues/2022-02-10-agents-not-allocating-ci.md
Labels `maven` and `maven-11` are not available.
> AWS agents not allocating

- content/issues/2022-03-30-infra.ci-maintenance.md
This PR closes https://github.com/jenkins-infra/helpdesk/issues/2840 (maintenance on infra.ci)
> close infra.ci maintenance

- config.yml
Title says all, this PR adds weekly.ci.jenkins.io to the statuspage.
> Add weekly.ci.jenkins.io to status page

- content/issues/2022-04-20-issue-ci.md
- content/issues/2022-04-21-issue-ci.md
- content/issues/2022-04-21-jira-lts-upgrade.md
This PR updates status.jenkins.io to close https://github.com/jenkins-infra/helpdesk/issues/2872.
It also closes the ci.jenkins.io incident from the same days.
> JIRA LTS Upgrade

- content/issues/2022-04-28-artifactory-ui.md
- content/issues/2022-05-02-migration-rating.md
update status messages for rating.jenkins.io migration + cleanup older issues on status.j
(edit)
- Related to https://github.com/jenkins-infra/helpdesk/issues/1627
- Closes https://github.com/jenkins-infra/helpdesk/issues/2904
> Chore: Issue to notify rating migration

- content/issues/2022-05-28-debian-installs-broken.md
LTS and weekly installs are temporarily unavailable from the standard locations.  Workaround is offered.
> Debian install is unavailable

- content/issues/2022-05-28-debian-installs-broken.md
- content/issues/2022-05-28-updates-flaky.md
Closes https://github.com/jenkins-infra/helpdesk/issues/2960
> close UC issues

- content/issues/2022-05-31-update-centernot-updated.md
Related to https://github.com/jenkins-infra/helpdesk/issues/2950
update-center and crawler certificate renew.
> chore(renew certif): close issue 2950

- content/issues/2022-09-02-jira-outage.md
> Jira down at 19:21 on 2022-09-02

- content/issues/2022-09-02-jira-outage.md
Updated the start of downtime and the resolution time based on monitoring data.
> Jira is running again

- .github/workflows/check-links.yaml
- .github/workflows/markdown-link-check-config.json
As this URL isn't reachable without a VPN connection, this PR configures the check-link GHA to ignore it so it doesn't fail when this URL is mentioned in status notices.
Ref: #224
> feat(check-link): ignore trusted.ci.jenkins.io links

- content/issues/2022-12-27-ci-restarting.md
Restarted to clear the job queue and remove idle agents.
> Document the restart for PR-1625

- content/issues/2023-01-24-ci-down.md
Will be online again after advisory is published.
> Plugin security advisory has ci.jenkins.io down

- content/issues/2023-02-03-s390x-agent-down.md
IBM will be doing some maintenance on the OSS Cloud that will require all servers to be stopped and restarted.  The outage window will be set to Friday 02/03/2023 from 4pm to 10pm ET.  Your server(s) will be automatically stopped and restarted during this time.  There is no action for you at this time.
> Announce s390x maintenance

- content/issues/2023-02-15-ci-down.md
Time is as reported by uptime robot.  Only checks once every 5 minutes, so may be wrong by as much as 5 minutes.
> ci.jenkins.io down for plugin advisory

- .github/workflows/check-links.yaml
- .github/workflows/hugo.yaml
- .github/workflows/updatecli.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402
> chore: pin GitHub actions with their SHA-1 instead of their version number

- .github/workflows/updatecli.yaml
- updatecli/updatecli.d/hugo.yaml
This PR follows up #257 .
It fixes the updatecli manifest and GHA workflow:
- Correct the GHA workflow to:
- Use the updatecli action's install mode (instead of execute in a closed environment), which removes the warning message `Unexpected input(s) 'command', 'flags', valid inputs are ['version']` from the GHA execution
- Use the `GITHUB_TOKEN` for the "Updatecli Diff" step so it's executed in every PR with the PR author's identity (relying on tidbex is only possible on the upstream branches)
- Correct the deprecated directives in the updatecli manifest
> chore(gha) fix the updatecli workflow to use the updatecli action "installation" mode

- content/issues/2023-03-11-jira-outage.md
I assumed that the date information would be included more visibly in the page.  It is in the page, but I did not immediately see it when I read the page.
@lemeurherve thanks for the quick review of the prior notice.  Added more text so that the date is included in the text, not just in the heading at the top of the page.
> Make Jira upgrade date more visible

- content/issues/2023-04-12-ci-outage.md
Announced in https://groups.google.com/g/jenkinsci-advisories/c/ccmIF1Vs-9A/m/GQei2TM9AAAJ
> Announce ci.jenkins.io down for plugin advisory

- content/issues/2023-07-06-jira-outage.md
https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25544 as coordinated from Mark Waite's account at the Linux Foundation.
> Announce 6 July 2023 Jira outage

- README.adoc
Also use a newer version of docker.
The version of docker-compose on my Debian 11 system was too old to run the site, while docker compose ran very well.
> Use docker compose instead of docker-compose locally

- content/issues/2023-07-06-jira-outage.md
Assure that users can find the status during the upgrade.
> Increase issues.jenkins.io to 'down' for July 6 upgrade

- content/issues/2023-07-12-ci-maintenance.md
If the plugin security advisory involves any plugins installed on ci.jenkins.io, then the controller will be restarted.
> Notify users of ci.jenkins.io restart tomorrow

- content/issues/2023-07-12-ci-maintenance.md
The ci.jenkins.io upgrade of the plugins is complete.
> Conclude the ci.jenkins.io outage

- content/issues/2023-12-06-artifactory-central-brownount.md
[Help desk ticket 3842](https://github.com/jenkins-infra/helpdesk/issues/3842) outlines the plan for this brownout.
> Announce Artifactory brownout Wed Dec 6, 2023

- content/issues/2023-12-06-artifactory-central-brownount.md
- content/issues/2023-12-07-x86medium-migration.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3827
Note I'm closing the jfrog brownout as it was finished in time yesterday
> open publick8s x86 nodepool migration

- content/issues/2023-12-15-artifactory-changes.md
Removing all mirrors of Apache Maven Central so that artifacts owned by Apache Maven Central will be delivered by Apache Maven Central.
> Announce Artifactory configuration change

- content/issues/2023-12-18-jira-outage.md
The JIRA instance at issues.jenkins.io, managed by the Linux Foundation team, will be down for up to 60 minutes beginning at 11:00 PM (UTC) Monday December 18, 2023 so that it can be restored from backup.  A spammer damaged over 1000 Jenkins issue reports on Dec 6, 2023.  We will restore a database backup that precedes the damage.
> Announce JIRA restore on Monday Dec 18, 2023

- content/issues/2023-12-15-artifactory-changes.md
[Jenkins developer list](https://groups.google.com/g/jenkinsci-dev/c/zTXeamwCMhA/m/V1Lmo9HzDQAJ) summarizes the Artifactory configuration changes.
The change is complete and is working as expected.  Tests that were performed to confirm the change include:
* Build Jenkins core on a freshly created virtual machine
* Build Jenkins plugin bill of materials weekly line on ci.jenkins.io
* Build 20+ plugins on a freshly created virtual machine, including the plugins where issues were detected during the brownout
* Build 250 most popular plugin repositories on an existing machine (a few of them only built successfully when using the pending pull request to test with Java 21)
* Release a plugin
The transition is complete and successful.
Log files contain the expected entries downloading artifacts …
> Resolve Artifactory notice

- content/issues/2023-12-27-jira-upgrade.md
Linux Foundation asked to do the upgrade during the holiday week.
Works great for the Jenkins project, since we have completed the weekly
release and do not have an LTS week until Jan 24, 2024.
> Announce Jira upgrade 2023-12-27

- content/issues/2023-12-27-jira-upgrade.md
Our contact at the Linux Foundation wrote:
> I was not able to complete the upgrade to 9.4.14 within the maintenance window, and have rolled back to the previous version of 9.4.7.
> 
> System updates were successfully applied, but the Jira upgrade will have to have further research and another scheduled maintenance window.
> 
> I'll post here again as soon as I find the path forward so we can schedule another maintenance window.
> Close the Jira maintenance window

- content/issues/2023-12-29-jira-upgrade.md
Discussed with the Linux Foundation administrators in IT-26310 ticket.
> Announce Jira upgrade 29 Dec 2023 at 18:00 UTC

- content/issues/2023-04-19-get.jenkins.io-incident.md
- content/issues/2024-01-08-get-jenkins-io-maintenance.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3828
> open get.jenkins.io maintenance operation

- content/issues/2024-03-12-jira-upgrade.md
Message from our contact at the Linux Foundation:
> I'd like to schedule the maintenance window for this upgrade. It appears that it can be accomplished in one step, going from 9.4.14 where we are now to 9.12.4. So that means less time than is required for multiple small upgrades. But the upgrade will trigger a full re-index. I'm guessing that could take about 30 minutes. Does that sound right based on your experience?  Other things to be aware of:
> 
> * 9.5 updates log4j and introduces breaking changes to the log4j config
> * 9.10 triggers the full re-index
> * 9.12 is the last version to support server licenses, but we are on data center, so this is fine
> * 9.12 introduces lots of changes to jira automation. Is that in use by you? …
> Schedule 2024-03-12 Jira upgrade

- content/issues/2024-03-12-jira-upgrade.md
Like last time, the linux foundation will post progress updates on its status page.
> Drop a link to the linux foundation status page for the upcoming Jira upgrade

- content/issues/2022-04-12-ci-outage.md
- content/issues/2022-05-01-ci-outage.md
TIme is not reported correctly by cState if a time zone offset is included in the data.  Always use timezone offset 00:00
> Use UTC time zone for all issues

- config.yml
this PR is addressing [issue#8](https://github.com/jenkins-infra/status/issues/8)
since time zone is always listed as UTC
the solution was updating the configuration file to specify the time zone in dates
> fix: add time zone to the dates

- content/issues/2024-05-02-ci.jenkins.io-outage.md
Updates are part of the plugin security advisory that was [announced to the Jenkins advisories mailing list](https://groups.google.com/g/jenkinsci-advisories/c/7u4u0lHbDEc/m/5CDiGkosBAAJ) two days ago.
> ci.jenkins.io down for plugin updates

- content/issues/2024-05-02-ci.jenkins.io-outage.md
Uptime robot reported time is included in the data.  Note that they only check every few minutes, so there is some inaccuracy in the reported value.
> Resolve ci.jenkins.io outage

- content/issues/2024-06-26-jira-upgrade.md
Ryan Day of the Linux Foundation team will perform the upgrade.
> Announce Jira upgrade Wed 26 Jun 2024 at 23:00 UTC

- content/issues/2024-07-03-maintenance-az-publick8s-1-28.md
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2196274746
status.jenkins.io issue created for the AZ publick8 cluster upgrade to kub 1.28
> Open issue for publick8 azure cluster upgrade to kub-1.28

- content/issues/2024-07-03-maintenance-az-publick8s-1-28.md
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2196274746
Issue can be closed as the AZ publick8s cluster was upgraded to kub 1.28
> closed issue for publick8s cluster as it is upgraded to kub 1.28

- content/issues/2024-09-06-UC-1hour-brownout-1.md
- content/issues/2024-09-09-UC-1hour-brownout-2.md
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069
Follow up of #537 
Keeping as draft until the first brownout is finished
> open UC brownout operation 2

- content/issues/2024-10-02-ci.jenkins.io-outage.md
Advisory was announced in the security group last week:
https://groups.google.com/g/jenkinsci-advisories/c/dszNG7XKdKU/m/IvT63YLiAgAJ
> ci.jenkins.io is down for a security update

- .github/workflows/hugo.yaml
- docker-compose.yaml
- netlify.toml
- updatecli/updatecli.d/hugo.yaml
Closes #455  and #473 
This PR switches to a new Docker image (https://docker.hugomods.com/docs/introduction/), currently community managed and widely used as the default for GoHugo since there are no official Docker image.
This image is part of the Docker OSS program (like Jenkins):
- Trustable
- No rate limit
- Support of arm64 (along usual x86_64)
Notes: 
- updatecli has been tested locally, but the check will fail until the PR is merged. We expect a PR to bump Hugo to 0.138.0 once merged
- The GHA workflow now reuses the docker compose to verify that both the site code AND the provided GoHugo setup works (in case of version bump)
> chore:  switch to `hugomods/hugo` Docker image, with Hugo `0.128.0`

- .github/workflows/hugo.yaml
- docker-compose.yaml
- updatecli/updatecli.d/hugo.yaml
Fixup of #551 
This PR removes the Docker Compose file YAML anchors as [not supported by `updatecli`](https://github.com/updatecli/updatecli/issues/1332) (creates PR with garbage in the YAML file making it unparseable).
It updates the `updatecli` manifest accordingly, along with the GHA workflow used to verify hugo.
Tested the updatecli manifest (as the check will fail in the PR) locally and got the following result:
```diff
diff --git a/docker-compose.yaml b/docker-compose.yaml
index 3cea750..5ac4177 100644
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,6 +1,6 @@
services:
status:
-    image: hugomods/hugo:ci-0.128.0
+    image: hugomods/hugo:ci-0.138.0
volumes:
- .:/src
ports:
diff --git a/netlify.toml b/netlify.toml
index 623ac48..ce68f10 100644
--- a/netlify.toml
+++ …
```
> chore: fix tracking of Hugo version by updatecli by removing YAML anchor in Docker Compose

- content/issues/2024-12-10-jira-upgrade-and-restart.md
Install more recent patch versions to resolve Jira administrative warnings.
> Update Jenkins Jira from 23:00 UTC to 23:59 UTC today

- content/issues/2025-02-06-ldap-outage.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4531
Closes the outage from #584 and #585
> Close LDAP outage

- layouts/services/list.html
Added inline styling `style="color: black;"` to explicitly set the text color for better visibility in `layouts/services/list.html` file.
The repository currently does not contain a global `.css` file, so modifying styles globally was not an option.
Tested with docker engine (suggested in readme)
Before :
After :
Please suggest any changes that needs to be done, if required
> Fix services page text color on Firefox

- content/issues/2025-02-14-aws.ci.jenkins.io-outage.md
Was resolved the same day that it was opened
Ongoing investigations of various issues related to the AWS transition are not serious enough to justify an outage report or a note that ci.jenkins.io is down.
> Resolve the ci.jenkins.io outage

- content/issues/2025-05-22-jdk21-runtime-controllers-agents-maintenances.md
as per https://github.com/jenkins-infra/helpdesk/issues/4121#issuecomment-2890355054
> start jdk21 runtime migration

- content/issues/2025-08-02-jira-tls-expired.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4757
> open jira expired certificate outage
