Gemfile
=> Add ascidoctor

config.yml
Don't show category name as you can see in this screenshot
=> Don't close category and hide their name

content/issues/2020-11-12-get-jenkins-io.md
I am using the announcement done on Twitter to set the resolve date. the service is working as expected 
=> Close get.jenkins.io incident

content/issues/2020-12-08-get-jenkins-io-dns-update.md, content/issues/2020-12-13-get-jenkins-io-dns-update.md
=> Announce get.jenkins.io dns update

config.yml, layouts/partials/http_response_time/archives.jenkins.io.html, layouts/partials/http_response_time/ci.jenkins.io.html, layouts/partials/http_response_time/issues.jenkins.io.html, layouts/partials/http_response_time/javadoc.jenkins.io.html, layouts/partials/http_response_time/jenkins.io.html, layouts/partials/http_response_time/plugins.jenkins.io.html, layouts/partials/http_response_time/wiki.jenkins.io.html
Add few response time dashboard which significantly slow down the page loading
- ci.jenkins.io
- www.jenkins.io
- wiki.jenkins.io
- issues.jenkins.io
- javadoc.jenkins.io
- archives.jenkins.io
- plugins.jenkins.io
=> Add Http response time graphs

content/issues/2021-03-21-update-sites-not-updating.md
Unsure whether this qualifies for https://github.com/jenkins-infra/status#informational-posts or not. The docs for this repo are pretty light.
=> Record update sites not updating since this morning

content/issues/2021-05-03-maintenance-ingress.md
=> Add ingress maintenance information

content/issues/2021-05-03-maintenance-ingress.md
=> Update ingress maintenance ticket

content/issues/2021-06-01-updates-job-blocked.md
=> Closing 2.296 update center incident

content/issues/2021-06-02-lts-windows.md
=> incident open for LTS windows package

content/issues/2021-06-02-lts-windows.md
=> closing incident for LTS 2.289.1

content/issues/2021-06-03-aks-sp-expiration.md
=> AKS SP renew open

content/issues/2021-06-03-no-aci-agents-for-ci-jenkins-io.md
=> close ci incident

content/issues/2021-06-07-repo-jenkins-ci-org.md
=> Open repo.jenkins-ci.org incident

content/issues/2021-06-07-repo-jenkins-ci-org.md
=> Close repo.jenkins-ci.org incident

content/issues/2021-06-03-aks-sp-expiration.md, content/issues/2021-06-08-ci-agents-disconnect.md
=> Open CI incident

content/issues/2021-06-08-fastly-outage.md
=> Open incident fastly

content/issues/2021-06-08-ci-agents-disconnect.md
=> close ci incident and trigger netlify

content/issues/2021-06-08-fastly-outage.md
=> Update fastly incident

content/issues/2021-06-17-maintenance-publick8s.md
=> Announce AKS 1.19 upgrade

content/issues/2021-06-17-maintenance-publick8s.md
=> Close AKS upgrade

content/issues/2020-06-13-maintenance-window copy.md
=> [INFRA-3010] Open maintenance window for ci.jenkins.io

content/issues/2020-06-13-maintenance-window copy.md
=> close INFRA_3010

content/issues/2021-07-07-update-center-not-refreshed.md
=> Update Center Fixed

content/issues/2021-07-07-update-center-not-refreshed.md
=> chore: clarify uc outage details

content/issues/2021-08-29-wiki-maintenance.md
Signed-off-by: Mark Waite <mark.earl.waite@gmail.com>
=> Resolve wiki maintenance

content/issues/2021-08-26-jfrog-maintenance.md
=> close jfrog operation

content/issues/2021-08-31-wiki-maintenance.md
=> Wiki running again

content/issues/2021-09-20-aks-maintenance.md
=> open: AKS maintenance fro 2021-09-20

content/issues/2021-09-20-aks-maintenance.md
=> close: AKS maintenance fro 2021-09-20

content/issues/2021-09-23-puppet-outage.md
=> open incident

content/issues/2021-10-05-maintenance-jira-rds.md
Convert database and tables to utf8mb5
Signed-off-by: Anton Baranov <abaranov@linuxfoundation.org>
=> open: jira rds maintenance

content/issues/2021-09-23-puppet-outage.md
=> closing puppet outage

content/issues/2021-10-05-maintenance-jira-rds.md
Signed-off-by: Anton Baranov <abaranov@linuxfoundation.org>
=> close: jira rds maintenanc

.github/workflows/check-links.yaml, .github/workflows/hugo.yaml, config.yml, content/issues/2021-06-02-lts-windows.md
Ref: https://issues.jenkins.io/projects/INFRA/issues/INFRA-3007
=> feat(gha): add github action to check for errors with Hugo and for broken links [INFRA-3007]

content/issues/2021-11-04-maintenance-window-ci.md, content/issues/2021-11-05-archives-jenkins-io-maintenance.md
- Log the ci.jenkins.io upgrade from 2.303.2 to 2.303.3
- Announce maintenance on archives.jenkins.io
=> Announce archives.jenkins.io maintenance"

content/issues/2021-11-18-jenkins-io-outage.md
=> open outage

content/issues/2021-11-18-jenkins-io-outage.md
Reverts jenkins-infra/status#96
=> Revert "chore: end of jenkins.io outage"

content/issues/2021-12-15-jira-outage.md
=> open JIRA outage 2021-12-15

content/issues/2021-12-20-maintenance-window-aks.md
=> open maintenance windows for nginx-ingress upgrade

content/issues/2022-01-13-issue-ci.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/2733
=> Open ci.jenkins.io disruption

content/issues/2022-01-13-issue-ci.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/2733#issuecomment-1012925200
=> chore: close ci.jenkins.io disruption notice

content/issues/2022-02-16-maintenance-window-ci.md
=> Schedule ci.jenkins.io plugin upgrades

content/issues/2022-02-10-agents-not-allocating-ci.md
=> EKS outage: move from down to notice and announce monday 14th operation

content/issues/2022-02-10-agents-not-allocating-ci.md
=> start operations on ci.jenkins.io

content/issues/2022-02-10-agents-not-allocating-ci.md, content/issues/2022-02-15-maintenance-window-ci.md
=> close EKS operation + notice for 2022-02-15 secrel

updatecli/values.github-action.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2753
=> chore: replace `updatebot@olblak.com`

content/issues/2022-03-04-artifactory-out-of-space.md
=> Artifactory outage incident

content/issues/2022-03-04-artifactory-out-of-space.md
=> close Jfrog incident

content/issues/2022-03-08-maintenance-k8s.md
=> open: announce k8s maintenance

content/issues/2022-04-08-maintenance-window-ingress-kubes.md
Related to https://github.com/jenkins-infra/helpdesk/issues/2875
=> open maintenance window

content/issues/2022-04-08-maintenance-window-ingress-kubes.md
This PRs closes the public maintenance windows and closes https://github.com/jenkins-infra/helpdesk/issues/2875
=> close maintenance windows

content/issues/2022-04-21-issue-ci.md
as per https://github.com/jenkins-infra/helpdesk/issues/2893 issue currently on ci.jenkins.io
=> disruption for ci.jenkins.io

content/issues/2022-04-28-artifactory-ui.md
=> open: jfrog UI outage

content/issues/2022-04-12-ci-outage.md, content/issues/2022-05-01-ci-outage.md, content/issues/2022-05-02-ci-outage.md
Thanks to Basil for help extracting diagnostic info
=> ci.jenkins.io outage closed on May 2, 2022

content/issues/2022-05-05-artifactory-down.md
Related to https://github.com/jenkins-infra/helpdesk/issues/2920
=> open jfrog incident - helpdesk#2920

content/issues/2022-05-07-maintenance-pkg-mirror-jenkins-io.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/2888#issuecomment-1120157745
=> open pkg VM maintenance

content/issues/2022-05-07-maintenance-pkg-mirror-jenkins-io.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/2888#issuecomment-1120178773
=> close pkg VM maintenance window

content/issues/2022-05-13-artifactory-down.md
Related to https://github.com/jenkins-infra/helpdesk/issues/2933
=> open jfrog incident - helpdesk#2933

content/issues/2022-05-13-artifactory-down.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/2933#issuecomment-1125967643
=> chore: close artifactory incident

content/issues/2022-05-17-infra-ci.md
=> Update AKS outage

content/issues/2022-05-17-infra-ci.md
=> close AKS outage

content/issues/2022-05-19-outage-updates.md
https://github.com/jenkins-infra/helpdesk/issues/2888#issuecomment-1131453254
=> end of issue 2888

content/issues/2022-05-27-maintenance-updates.md
Part of https://github.com/jenkins-infra/helpdesk/issues/2888
=> open maintenance for the VM pkg.origin.jenkins.io (updates.jenkins.io)

content/issues/2022-05-27-maintenance-updates.md
=> close maintenance

content/issues/2022-05-27-ssl-certificate-expired.md
- Report SSL certificate expired
- Don't include hyperlinks, fails the checks
=> Fix broken links

content/issues/2022-05-28-debian-installs-broken copy.md, content/issues/2022-05-28-debian-installs-broken.md
=> close pkg incident + open flaky for UC

content/issues/2022-06-28-maintenance-AKS-k8s.md
as per https://github.com/jenkins-infra/helpdesk/issues/2930 noticing of maintenance operation
=> Announce AKS Kubernetes upgrade to 1.22

content/issues/2022-07-04-artifactory-slow.md
=> open jfrog incident

content/issues/2022-07-06-ci-maintenance.md
Related to:
- https://github.com/jenkins-infra/helpdesk/issues/2961
- https://github.com/jenkins-infra/helpdesk/issues/3031
- https://github.com/jenkins-infra/helpdesk/issues/2984
=> open ci.j maintenance windows

content/issues/2022-08-09-maintenance-ingress.md
=> open: Kubernetes maintenance for nginx and falco

content/issues/2022-08-09-maintenance-ingress.md
=> close k8s maintenance

content/issues/2022-08-30-vpn-outage.md
=> vpn outage

content/issues/2022-10-24-maintenance-EKS-k8s-1-23.md
we start a maintenance on EKS cluster to upgrade to kubernetes 1.23
=> feat(EKS/upgrade): upgrade EKS cluster to 1.23

content/issues/2022-11-01-ci.j-maintenance.md, content/issues/2022-11-02-ci.j-maintenance.md
=> announce maintenances on ci.jenkins.io

content/issues/2022-12-09-artifactory-maintenance.md
=> add initial announcment for jfrog maintenance

content/issues/2022-12-09-artifactory-maintenance.md
=> update jfrog maintenance infos

content/issues/2022-12-09-artifactory-maintenance.md
Draft until JFrog confirmation.
=> End of Artifactory maintenance

content/issues/2023-01-24-ci-down.md
uptime monitor reports service restored at 2023-01-24 08:20:33 Denver
time.
=> ci.jenkins.io is up

content/issues/2023-02-03-s390x-agent-down.md
Agent is online and ready to handle requests
=> s390x agent maintenance is complete

content/issues/2023-02-15-ci-maintenance.md
=> end of maintenance ci

content/issues/2023-02-22-maintenance-eks-k8s-1-24.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
=> Close 2023-02-22-maintenance-eks-k8s-1-24.md

content/issues/2023-02-23-maintenance-aks-k8s-1-24.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
=> Close 2023-02-23-maintenance-aks-k8s-1-24.md

content/issues/2023-03-07-maintenance-prodpublick8s-sp.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3433
=> Open the maintenance for `prodpublick8s` 's SP renewal

content/issues/2023-03-09-bots-migrations.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/2844
=> Create 2023-03-09-bots-migrations.md (#260

content/issues/2023-03-09-bots-migrations.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/2844
=> Close 2023-03-09-bots-migrations.md (#265

.github/workflows/updatecli.yaml
Follow-up of #258 
Not completely sure of this PR, these comments seem to contradict themselves, WDYT?
=> chore(gha): update comments above `UPDATECLI_GITHUB_TOKEN`

content/issues/2023-04-12-ci-maintenance.md
Ref. https://www.jenkins.io/security/advisory/2023-04-12/
=> Close the maintenance windows on ci.jenkins.io for the 2023-04-12 advisory

content/issues/2023-04-19-get.jenkins.io-incident.md
Opening incident for https://github.com/jenkins-infra/helpdesk/issues/3525
=> open incident for helpdesk-3525

content/issues/2023-05-26-publicheathscore-migrations.md
opening issue for PHS migration to publicK8S
=> feat(PHS): Migration PHS to publick8s

content/issues/2023-05-26-incrementals-publisher-migration.md, content/issues/2023-05-26-publicheathscore-migrations.md
https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1564517009
=> open: incremental migration

content/issues/2023-05-26-incrementals-publisher-migration.md
https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1564632990
=> close incremental migration

content/issues/2023-06-01-uplink-migration.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1571588945
=> Close 2023-06-01-uplink-migration.md

content/issues/2023-06-02-trusted.ci-migration-to-azure.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3486
=> open trusted migration

content/issues/2023-06-02-accountapp-migration-to-publick8s.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351
=> Close 2023-06-02-accountapp-migration-to-publick8s.md

content/issues/2023-06-02-trusted.ci-migration-to-azure.md
https://github.com/jenkins-infra/helpdesk/issues/3486#issuecomment-1573305761
=> close trusted migration

content/issues/2023-06-08-artifactory-operation.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3599
=> open operation for JFrog jgit brownout

content/issues/2023-06-08-ldap-migration-to-publick8s.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
=> Close 2023-06-08-ldap-migration-to-publick8s.md

content/issues/2024-06-12-mirrorbits-migration-to-publick8s.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1586969797
=> Close 2024-06-12-mirrorbits-migration-to-publick8s.md

content/issues/2023-06-13-plugin-site-migration-to-publick8s.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1588038925
=> Close 2023-06-13-plugin-site-migration-to-publick8s.md

content/monitoring/index.adoc
https://status.jenkins.io/monitoring/
=> feat: add a link to helpdesk for requesting new public monitors

content/issues/2023-06-21-digitalocean-incident.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3582 and https://github.com/jenkins-infra/helpdesk/issues/3633
=> close DO incident

content/issues/2023-07-04-ci-maintenance.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3535
=> close CI maintenance

content/issues/2023-07-07-maintenance-aks-k8s-1-25.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3582
=> Open AKS 1.25 upgrade

content/issues/2023-07-06-jira-outage.md
See the mail message on the developers list
https://groups.google.com/g/jenkinsci-dev/c/XWgSMmj864M/m/6GSHA6r-BgAJ
=> Extend issues.jenkins.io upgrade time

content/issues/2023-07-06-jira-outage.md
As announced in the [developer mailing list](https://groups.google.com/g/jenkinsci-dev/c/Qx4QtAFIdoA/m/dFDi_1ECBwAJ), the upgrade is complete.
=> issues.jenkins.io upgrade is complete

content/issues/2023-08-28-cert.ci.jenkins.io-maintenance.md
https://github.com/jenkins-infra/helpdesk/issues/3688
=> close operation

content/issues/2023-09-02-ci.jenkins.io-maintenance.md
Mark Waite updated Pipeline plugins and restart hung
=> Report ci.jenkins.io outage due to plugin upgrade

content/issues/2023-09-02-ci.jenkins.io-maintenance.md
Resolved by Damien doing a service restart
=> ci.jenkins.io plugin upgrade outage is resolved

content/issues/2023-10-19-publik8s-public-nginx-ingress-arm64-migration.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1713522131
=> Announce public nginx ingress migration to arm64

content/issues/2023-10-25-mirrorbits-arm64-migration.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619 & https://github.com/jenkins-infra/kubernetes-management/pull/4577#issuecomment-1778619413
=> Open 2023-10-25-mirrorbits-arm64-migration

content/issues/2023-10-25-mirrorbits-arm64-migration.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619
=> Postpone 2023-10-25-mirrorbits-arm64-migration.md

content/issues/2023-10-31-uplink-arm64-migration-preparation.md
Related: https://github.com/jenkins-infra/kubernetes-management/pull/4607#pullrequestreview-1704815716
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619
=> Open 2023-10-31-uplink-arm64-migration-preparation

content/issues/2023-10-31-uplink-arm64-migration.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619
=> Close 2023-10-31-uplink-arm64-migration.md

content/issues/2023-11-02-activate-delete-option-on-jenkins-io-build.md
Refs:
- https://github.com/jenkins-infra/helpdesk/issues/3360
- https://github.com/jenkins-infra/jenkins.io/pull/6677
=> Open 2023-11-02-activate-delete-option-on-jenkins-io-build

content/issues/2023-11-02-activate-delete-option-on-jenkins-io-build.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3360#issuecomment-1790899357
=> Postpone 2023-11-02-activate-delete-option-on-jenkins-io-build

content/issues/2023-11-02-activate-delete-option-on-jenkins-io-build.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3360#issuecomment-1792076471
=> Reopen 2023-11-02-activate-delete-option-on-jenkins-io-build

content/issues/2023-11-02-activate-delete-option-on-jenkins-io-build.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3360
=> Close helpdesk3360-activate-delete-jenkins-io

content/issues/2023-11-06-maintenance-eks-k8s-1-26.md
Related to https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1794913444
=> Open EKS 1.26 upgrade operation

content/issues/2023-11-06-cert-manager-arm64-migration.md, content/issues/2023-11-06-datadog-cluster-agent-arm64-migration.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
=> Open 2023-11-06-arm64-migration(s)

content/issues/2023-11-06-datadog-cluster-agent-arm64-migration.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
=> Close 2023-11-06-datadog-cluster-agent-arm64-migration.md

content/issues/2023-11-06-maintenance-eks-k8s-1-26.md
https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1794913444
=> close kube 1.26 EKS upgrade

content/issues/2023-11-06-cert-manager-arm64-migration.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
=> Close 2023-11-06-cert-manager-arm64-migration.md

content/issues/2023-07-07-maintenance-aks-1.26-privatek8s.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1797928819
=> open kube 1.26 privatek8s operation

content/issues/2023-11-09-maintenance-aks-1.26-publick8s.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1803566680
=> close 1.26 Kubernetes upgrade

content/issues/2023-11-17-pluginsite-arm64-migration.md
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1810363708
=> open migration pluginsite and pluginsite issue to arm64

content/issues/2023-11-20-mirrorbits-httpd-rsyncd-arm64-migration.md
https://github.com/jenkins-infra/kubernetes-management/pull/4691
=> closing issue migration arm64 httpd and rsyncd from updates/mirrobits

content/issues/2023-11-22-azure-jenkins-controllers-ops.md
Forgot to close the operation: this PR fixes this mistake.
=> close(controllers operation)

content/issues/2023-11-27-weekly-ci-arm64-migration.md
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1825661926
=> open migration weekly to arm64

content/issues/2023-12-04-x86medium-migration.md
as per https://github.com/jenkins-infra/helpdesk/issues/3827
=> open x86medium migration

content/issues/2023-12-07-jira-outage.md
> I’ve merged the patch to update the JDK version, poked Puppet, and the JIRA service has restarted with the new JDK version.
> 
> This work should now be complete.
> 
> - Matt Watkins
=> Resolve Jira maintenance - completed successfully

content/issues/2023-12-13-ci.jenkins.io-outage.md
=> ci.jenkins.io is down, investigation in progress

content/issues/2023-12-13-ci.jenkins.io-outage.md
=> Resolve ci.jenkins.io outage

content/issues/2023-12-18-jira-outage.md
Confirmed resolved one hour ago.
=> Resolve JIRA outage

content/issues/2024-01-08-get-jenkins-io-maintenance.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3828
=> Close maintenance of `get.jenkins.io`

content/issues/2024-01-19-ldap-maintenance.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-1898378430
=> open LDAP 1.0.1 bump maintenance

content/issues/2024-01-25-ci.jenkins.io-migration.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3913
=> open ci.jenkins.io migration ops

content/issues/2024-01-25-ci.jenkins.io-migration.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3913
=> close operation for ci.j

content/issues/2024-01-26-get.jenkins.io-migration.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3917
=> open helpdesk-3917 maintenance window

content/issues/2024-01-26-get.jenkins.io-migration.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3917#issuecomment-1911988727
=> close get.jenkins.io operation

content/issues/2024-01-30-get-jenkins-io-issue.md, content/issues/2024-01-30-get-jenkins-io-latest-issue.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3927
=> Open 2024-01-30-get-jenkins-io-latest-issue

content/issues/2024-01-30-get-jenkins-io-latest-issue.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3927#issuecomment-1917962734
=> Close 2024-01-30-get-jenkins-io-latest-issue

content/issues/2024-02-07-ci-down.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3934#issuecomment-1932273142
=> Close 2024-02-07-ci-down.md

content/issues/2024-02-28-plugins.jenkins.io-storage-account-migration.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1964568638
=> Open 2024-02-28-plugins.jenkins.io-storage-account-migration

content/issues/2024-02-28-plugins.jenkins.io-storage-account-migration.md
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1964568638
=> Close 2024-02-28-plugins.jenkins.io-storage-account-migration

content/issues/2024-07-03-maintenance-aks-k8s-1-27.md
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1976757473
=> open bump kubernetes 1.27

content/issues/2024-03-12-jira-upgrade.md
=> JIRA upgrade is complete

content/issues/2024-18-03-maintenance-az-privatek8s-1-27.md
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991178802
=> closing issue kub1.27 privatek8s

content/issues/2024-19-03-maintenance-az-publick8s-1-27.md
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991181964
=> open publick8s kub 1.27 migration

content/issues/2024-03-28-acp-1.0.0.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3969
=> open ACP 1.0.0

content/issues/2024-04-11-infraci-maintenance.md
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
=> open infra.ci ZRS migration

content/issues/2024-04-11-infraci-maintenance.md
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
=> close helpdesk 3823 migration infra.ci to zrs

content/issues/2024-04-23-ci-maintenance.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4052
=> closing ci.jenkins.io operation for helpdesk-4052

content/issues/2024-05-02-ci.jenkins.io-outage.md, content/issues/2024-05-06-ci.jenkins.io-datadog-plugin.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4080#issuecomment-2095831304
=> open(ci.jenkins.io) datadog plugin downgrade

content/issues/2024-06-05-RPU-trusted.md
as per https://github.com/jenkins-infra/helpdesk/issues/4122
=> open RPU build stuck

content/issues/2024-06-25-maintenance-aks-k8s-cijioa-1-28.md
as per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2182701643
=> open issue for kub 1.28 upgrade for cijioagent1

content/issues/2024-06-26-ci-maintenance.md
Ref. https://groups.google.com/g/jenkinsci-advisories/c/MokuNdWXGfg
=> open CI maintenance

content/issues/2024-06-27-maintenance-az-privatek8s-1-28.md
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2190936375 issue created
=> open issue for kub 1.28 upgrade for privatek8s

content/issues/2024-06-26-jira-upgrade.md, content/issues/2024-06-27-maintenance-az-privatek8s-1-28.md
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2190936375
Issue closed as upgrade to kub 1.28 was completed.
=> Closed issue for Privatek8s cluster upgrade and jira upgrade.

content/issues/2024-07-02-publicheathscore-outage.md, content/issues/2024-07-02-weekly-core-release-2.465-failed.md
Related to https://github.com/jenkins-infra/helpdesk/issues/4152 AND to the failing 2.465 release (https://matrix.to/#/!JlkqzpdEnsUUuVtjgE:matrix.org/$smDaTaJcu_VwzHd5JNB-3aXDxymiHoI7McGPddynIBA?via=gitter.im&via=matrix.org)
=> open incidents for a chaotic Tuesday 2 July

content/issues/2024-07-05-maintenance-az-publick8s-arm64.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/3837
=> open operation for LDAP + ACP for helpdesk-3837

content/issues/2024-08-22-ci-maintenance.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4236
=> open ci.jio maintenance for datadog plugin upgrade

content/issues/2024-08-22-maintenance-aks-cijioagents1-1-28.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2304516597
=> open ci.jio-agents1 1.29.x upgrade operation

content/issues/2024-08-22-ci-maintenance.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4236
=> close ci.jio operation

content/issues/2024-08-22-maintenance-aks-cijioagents1-1-29.md
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2304516597
=> close AKS 1.29 upgrade for ci.jio

content/issues/2024-08-23-maintenance-az-privatek8s-1-29.md, content/issues/2024-08-23-maintenance-az-publick8s-1-29.md
Related to https://github.com/jenkins-infra/helpdesk/issues/4161
=> open AKS 1.29 operations for public and private clusters

content/issues/2024-09-06-UC-1hour-brownout-1.md
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069
=> open UC brownout operation 1

content/issues/2024-09-09-azure-VMs-outage.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4287
=> open Azure outage

content/issues/2024-09-10-UC-24hour-brownout-3.md, content/issues/2024-09-25-UC-24hour-brownout-4.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
=> add brownouts 3 (closed) and 4 (open)

content/issues/2024-10-16-get-jenkins-io-redis-cleanup.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4330
=> open operation for helpdesk-4330 - get.jenkins.io redis reset

content/issues/2024-10-24-UC-24hour-brownout-5.md
ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2434782765
=> open 5th UC brownout

content/issues/2024-11-07-UC-24hour-brownout-6.md
Ref https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2450524487
=> open brownout updatecenter 6

content/issues/2024-11-07-UC-24hour-brownout-6.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2456695327
=> close 6th Azure UC brownout

content/issues/2024-11-11-jira-upgrade-and-restart.md
Confirmed complete by Ryan Day of the Linux Foundation and confirmed operational by my testing.
=> Close issue.jenkins.io update

content/issues/2024-11-28-outage-uc.md
Closes https://github.com/jenkins-infra/helpdesk/issues/4427
Closes https://github.com/jenkins-infra/helpdesk/issues/4428
=> Close UC 2024-11-28-outage-uc.md

content/issues/2024-11-28-outage-uc.md, content/issues/2024-12-05-mirrorbits-gelocation-disruption.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4441
=> open mirrorbits disruption

content/issues/2024-12-10-jira-upgrade-and-restart.md
Also correct the time and day of week in body
=> Fix start and end time of Jira update

content/issues/2024-12-05-mirrorbits-gelocation-disruption.md
Refer to:
* https://github.com/jenkins-infra/helpdesk/issues/4441
=> Close get.jenkins.io disruption

content/issues/2024-12-22-artifactory-outage.md
=> Resolve the Artifactory outage

content/issues/2025-01-08-ci.jenkins.io-azure-outage.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4490
=> open Azure + ci.jenkins.io Windows containers outage

content/issues/2025-01-08-ci.jenkins.io-azure-outage.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4490
=> close Azure outage

content/issues/2025-02-06-ldap-outage.md
Show users we are aware of the issue.
=> Start an LDAP server outage

content/issues/2025-02-06-ldap-outage.md
Progress will be tracked in the help desk ticket, not on the status web site.
=> Add help desk link in issue description

content/issues/2025-02-13-ci-migration.md
finish https://github.com/jenkins-infra/helpdesk/issues/4315
=> close ci.jio migration

content/issues/2025-02-19-maintenance-aws-cijioagents2-1-30.md
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2666362598
=> open issue cijioagents2 upgrade kubernetes 1.30

content/issues/2025-02-19-maintenance-aws-cijioagents2-1-30.md
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2666362598
=> close cijioagents2 kub 1.30 upgrade

content/issues/2025-02-19-maintenance-azure-privatek8s-1-30.md
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2668175339
=> open issue privatek8s upgrade kubernetes 1.30

content/issues/2025-02-19-maintenance-azure-publick8s-1-30.md
see https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663553626
=> open issue publick8s upgrade kubernetes 1.30

content/issues/2025-02-19-maintenance-azure-publick8s-1-30.md
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663553626
=> close issue publick8s upgrade kubernetes 1.30

content/issues/2025-02-19-maintenance-azure-privatek8s-1-30.md
Using the phrasing change to confirm that latest Hugo version update is correctly generating the site.
=> Small phrasing change in privatek8s resolved outage

content/issues/2025-03-05-ci-maintenance-sec-advisory.md
Update was completed the same day that it was opened.
=> Close ci.jenkins.io security update

content/issues/2025-04-09-ci-migration-to-azure.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620
=> open ci.jio status migration to Azure

content/issues/2025-04-24-maintenance-azure-publick8s-1-31.md
as per https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674545933
=> open issue publick8s upgrade kubernetes 1.31

content/issues/2025-04-23-maintenance-azure-privatek8s-1-31.md
as per https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674551720
=> open issue privatek8s upgrade kubernetes 1.31

content/issues/2025-04-23-maintenance-azure-privatek8s-1-31.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4546
=> Close `privatek8s`kubernetes 1.31 upgrade operation

content/issues/2025-04-24-maintenance-azure-publick8s-1-31.md
as per https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674545933
=> close publick8s kub 1.31 upgrade

content/issues/2025-04-29-maintenance-azure-privatek8s-1-31.md
https://github.com/jenkins-infra/helpdesk/issues/4250
=> open operation

content/issues/2025-05-22-jdk21-runtime-controllers-agents-maintenances.md
change time of operation for 5PM to 1PM
=> fix wrong time zone

content/issues/2025-07-29-infra.ci-down.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4753
=> close infra.ci outage

content/issues/2025-08-02-jira-tls-expired.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4757#issuecomment-3148083584
=> close JIRA outage

content/issues/2025-08-06-UC-enforce-HTTPS.md
Ref. https://github.com/jenkins-infra/helpdesk/issues/4758
=> Open operation for Update Center enforced HTTPS

content/issues/2025-09-25-azure-publick8s-1-32-adn-migration.md
Related to  https://github.com/jenkins-infra/helpdesk/issues/4617
=> open migration of pubick8s to new cluster with Kubernetes 1.32

content/issues/2025-10-02-usage-migration.md
as per https://github.com/jenkins-infra/helpdesk/issues/1626
=> open issues migration usage.jenkins.io to do
